# This GitHub workflow is only needed for python package releases which are supposed to be published on pypi.
# It requires the Github "environments" feature (see instructions below) it might not be available for private free accounts (but works for public or organization repos).
# After creating the "release" environment in the Github repo settings, you need to enter your Github organization/username + repo name + "release.yml" workflow file name in the PyPI UI to make this work.

# This workflow uploads a Python Package using uv when a release is created.
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on:
  release:
    types: [ created, edited ]

jobs:
  tests:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: src
    steps:
      - uses: actions/checkout@v7.0.1
      - name: Install uv
        uses: astral-sh/setup-uv@v9.0.0
        with:
          python-version: "3.14"
      - name: Run the tests
        run: |
          uv run --locked --group tests pytest
      - name: Run the type checks
        run: |
          uv run --locked --group type_check mypy --show-error-codes --strict src/bdew_datetimes
          uv run --locked --group type_check mypy --show-error-codes --strict tests
      - name: Run the linter
        run: |
          uv run --locked --group linting ruff check .
      - name: Run the formatter (check only)
        run: |
          uv run --locked --group linting ruff format --check .
      - name: Run the spell check
        run: |
          uv run --locked --group spell_check codespell --ignore-words=domain-specific-terms.txt src/bdew_datetimes
          uv run --locked --group spell_check codespell --ignore-words=domain-specific-terms.txt README.md

  build-n-publish:
    name: Build and publish Python 🐍 distributions 📦 to PyPI and TestPyPI
    runs-on: ubuntu-latest
    # Specifying a GitHub environment, # Specifying a GitHub environment, which is strongly recommended by PyPI: https://docs.pypi.org/trusted-publishers/adding-a-publisher/
    # you have to create an environment in your repository settings and add the environment name here
    environment: release
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    needs: tests
    steps:
      - uses: actions/checkout@v7.0.1
      - name: Install uv
        uses: astral-sh/setup-uv@v9.0.0
        with:
          python-version: "3.14"
      - name: Build wheel and source distributions
        run: |
          uv build
      - name: Publish distribution 📦 to PyPI
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          uv publish --trusted-publishing=automatic
